name = "EquivalenceClassesConstructor"
uuid = "b0d053df-94a8-4c0c-9762-4584a2fcd8b0"
authors = ["Julian Stobbe <Atomtomate@gmx.de> and contributors"]
version = "0.1.0"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
DocumenterTools = "35a29f4d-8980-5a13-9543-d66fff28ecb8"

[compat]
DocumenterTools = "0.1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
